// File automatically generated by swift-bridge.
#include <stdbool.h>
typedef struct __swift_bridge__$MessageWrapper { void* message; } __swift_bridge__$MessageWrapper;
typedef struct __swift_bridge__$Option$MessageWrapper { bool is_some; __swift_bridge__$MessageWrapper val; } __swift_bridge__$Option$MessageWrapper;
typedef struct __swift_bridge__$ParserOptions { bool ignore_tag; bool requires_other_clause; bool should_parse_skeletons; bool capture_location; void* locale; } __swift_bridge__$ParserOptions;
typedef struct __swift_bridge__$Option$ParserOptions { bool is_some; __swift_bridge__$ParserOptions val; } __swift_bridge__$Option$ParserOptions;
void* __swift_bridge__$icu_message_format(struct __swift_bridge__$MessageWrapper message, struct __swift_bridge__$ParserOptions options);


